### ISSUE TITLE
Ctrl-g binding removed, but still in doc

### ISSUE THREAD

**Issue by studgeek** [nfultz/fzf-jump#2]
The commit https://github.com/nfultz/fzf-jump/commit/532c83c67348ab0373e1b1967350bd255c126a54 removed the Ctrl-g binding, but its still in the README.md. Assuming it was removed for a reason, perhaps the README.md should be updated with how to manually add it? Or a second script could be provided that users can source if that want the binding?

**Comment by nfultz** [comment]
I'll update the README. Surprised anyone else found this useful. Cheers.

**Comment by studgeek** [comment]
I use it constantly. It's actually my favorite part of fzf so far :). Thank
you for it!
